### ISSUE TITLE
more tables packges

### ISSUE THREAD

**Issue by shannonpileggi** [ivelasq/2021-10-27_rladies-jozi-presentation#2]
Hi Isabella!  Great presentation! If you are interested in keeping the tabling packages on slide 34 comprehensive, two more are `arsenal` & `gtsummary`.

**Comment by ivelasq** [comment]
Thanks so much, Shannon! 👍 Added in https://github.com/ivelasq/2021-10-27_rladies-jozi-presentation/commit/0db94e8df7ccbb4edb4ab83f6a97ed0199688e83.
